# Generated by Django 4.2.7 on 2025-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='show_in_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
